# Generated by Django 4.1.6 on 2023-02-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_work_experience_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_experience',
            name='Place',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
