# Generated by Django 4.1.6 on 2023-02-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_work_experience_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work_experience',
            name='Date',
        ),
        migrations.AddField(
            model_name='work_experience',
            name='End_Date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='work_experience',
            name='Start_Date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
