# Generated by Django 4.1.6 on 2023-02-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_work_experience_date_work_experience_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='is_code_skill',
            field=models.BooleanField(default=False),
        ),
    ]
