# Generated by Django 4.1.6 on 2023-02-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_skill_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='link',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='name',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
